jamebal/jmal-cloud-server

src/main/java/com/jmal/clouddisk/oss/web/WebOssService.java

修复oss中分页数据无法正常获取，只能拿去第一页。
在查询oss文件列表时，先过滤再设置属性优化效率。

fix:oss查询列表分页不正常

---

src/main/java/com/jmal/clouddisk/service/impl/CommonFileService.java
src/main/java/com/jmal/clouddisk/util/CaffeineUtil.java

fix: 修复上传压缩包有几率报错的问题 [#102](https://github.com/jamebal/jmal-cloud-view/issues/102)

fix: 修复上传压缩包有几率报错的问题

---

src/main/java/com/jmal/clouddisk/oss/web/WebOssService.java
src/main/java/com/jmal/clouddisk/service/Constants.java
src/main/java/com/jmal/clouddisk/service/impl/CommonFileService.java
src/main/java/com/jmal/clouddisk/service/impl/FileServiceImpl.java

fix: 修复上传文件夹卡住进度条的问题

---

src/main/java/com/jmal/clouddisk/config/FileProperties.java
src/main/java/com/jmal/clouddisk/controller/rest/FileController.java
src/main/java/com/jmal/clouddisk/controller/sse/SseController.java
src/main/java/com/jmal/clouddisk/listener/FileMonitor.java
src/main/java/com/jmal/clouddisk/model/FileDocument.java
src/main/java/com/jmal/clouddisk/model/Trash.java
src/main/java/com/jmal/clouddisk/service/IFileService.java
src/main/java/com/jmal/clouddisk/service/impl/CommonFileService.java
src/main/java/com/jmal/clouddisk/service/impl/FileServiceImpl.java
src/main/resources/file.yml

fix: https://github.com/jamebal/jmal-cloud-view/issues/195

perf: 优化删除操作和移动操作

---

src/main/java/com/jmal/clouddisk/oss/minio/MinIOService.java

fix: 修复minio上传文件超过5G会丢失文件的问题

---

src/main/java/com/jmal/clouddisk/lucene/LuceneService.java

link: https://github.com/jamebal/jmal-cloud-view/issues/316

perf: 优化全文搜索，同时匹配多个关键字(使用空格隔开)可缩小搜索范围

---

src/main/java/com/jmal/clouddisk/service/impl/AuthServiceImpl.java

fix: https://github.com/jamebal/jmal-cloud-view/issues/271

fix: 修复ldap账号格式判断

---

src/main/java/com/jmal/clouddisk/lucene/LuceneService.java
src/main/java/com/jmal/clouddisk/lucene/RebuildIndexTaskService.java

link: https://github.com/jamebal/jmal-cloud-view/issues/321

fix: 修复重建索引有时会卡住的问题

---

src/main/java/com/jmal/clouddisk/model/SharerDTO.java
src/main/java/com/jmal/clouddisk/service/impl/ShareServiceImpl.java

fix: https://github.com/jamebal/jmal-cloud-server/issues/158

fix: 修复分享链接里的文件没有使用预览配置打开的问题

---

src/main/java/com/jmal/clouddisk/lucene/LuceneService.java

fix: https://github.com/jamebal/jmal-cloud-view/issues/286

perf: 修复大量文件重建索引卡住的问题

---

src/main/java/com/jmal/clouddisk/lucene/RebuildIndexTaskService.java
src/main/java/com/jmal/clouddisk/media/VideoProcessService.java

link：https://github.com/jamebal/jmal-cloud-view/issues/328

perf: 优化重建索引

---

src/main/java/com/jmal/clouddisk/service/impl/AuthServiceImpl.java

link：https://github.com/jamebal/jmal-cloud-view/issues/328

perf: 优化验证LDAP DN(Distinguished Name)字符串是否有效

---

src/main/java/com/jmal/clouddisk/office/callbacks/implementations/SaveCallback.java
src/main/java/com/jmal/clouddisk/service/impl/CommonFileService.java

link: https://github.com/jamebal/jmal-cloud-view/issues/353

fix: 修复挂载目录中office文件修改不生效的问题

---

src/main/java/com/jmal/clouddisk/controller/rest/FileController.java
src/main/java/com/jmal/clouddisk/service/IFileService.java
src/main/java/com/jmal/clouddisk/service/impl/FileServiceImpl.java

link: https://github.com/jamebal/jmal-cloud-view/issues/338

feat: 新增下载文件操作日志

---

src/main/java/com/jmal/clouddisk/service/impl/LogService.java

link: https://github.com/jamebal/jmal-cloud-view/issues/357

fix: 修复超级管理员无法查询日志的问题

---

pom.xml
src/main/java/com/jmal/clouddisk/ocr/OcrLiteOnnxService.java
src/main/java/com/jmal/clouddisk/ocr/OcrService.java
src/main/java/com/jmal/clouddisk/ocr/TesseractOcrConfig.java
src/main/java/com/jmal/clouddisk/ocr/TesseractService.java

link: https://github.com/jamebal/jmal-cloud-view/issues/370

fix: 修复部分ORC任务卡住的问题

---

src/main/java/com/jmal/clouddisk/service/impl/CommonFileService.java

link: https://github.com/jamebal/jmal-cloud-view/issues/376

fix: 修复重建索引时导致服务无法访问的问题

---

src/main/java/com/jmal/clouddisk/lucene/ReadContentService.java

link: https://github.com/jamebal/jmal-cloud-view/issues/377

fix: 修复部分pdf文档读取失败的问题

---

src/main/java/com/jmal/clouddisk/service/impl/AuthServiceImpl.java

link: https://github.com/jamebal/jmal-cloud-view/issues/388

perf: 优化LDAP配置格式校验,对大小写不敏感

---

src/main/java/com/jmal/clouddisk/lucene/EtagService.java
src/main/java/com/jmal/clouddisk/lucene/LuceneService.java
src/main/java/com/jmal/clouddisk/model/FileDocument.java
src/main/java/com/jmal/clouddisk/model/FileIntroVO.java
src/main/java/com/jmal/clouddisk/service/Constants.java
src/main/java/com/jmal/clouddisk/service/impl/CommonFileService.java
src/main/java/com/jmal/clouddisk/service/impl/FileServiceImpl.java

- 新增 EtagService 类，实现文件和文件夹的 ETag 更新逻辑
- 在 FileDocument 模型中添加与 ETag 相关的字段
- 更新 FileServiceImpl 和 LuceneService，集成 ETag功能
- 在 Constants 中添加 ETag 相关的常量

feat: 添加 ETag服务并更新相关功能

---

src/main/java/com/jmal/clouddisk/controller/rest/FileController.java
src/main/java/com/jmal/clouddisk/controller/rest/FileVersionController.java
src/main/java/com/jmal/clouddisk/controller/sse/SseController.java
src/main/java/com/jmal/clouddisk/exception/CommonExceptionHandler.java
src/main/java/com/jmal/clouddisk/lucene/EtagService.java
src/main/java/com/jmal/clouddisk/office/OfficeHistory.java
src/main/java/com/jmal/clouddisk/office/callbacks/implementations/SaveCallback.java
src/main/java/com/jmal/clouddisk/office/model/Track.java
src/main/java/com/jmal/clouddisk/service/IFileVersionService.java
src/main/java/com/jmal/clouddisk/service/IUserService.java
src/main/java/com/jmal/clouddisk/service/impl/FileVersionServiceImpl.java
src/main/java/com/jmal/clouddisk/service/impl/MarkdownServiceImpl.java
src/main/java/com/jmal/clouddisk/service/impl/UserServiceImpl.java
src/main/resources/logback.xml

feat: 添加 office历史文件列表接口

---

docker-entrypoint.sh

- 移除了对 /jmalcloud 目录的权限设置
link: https://github.com/jamebal/jmal-cloud-view/issues/426

build: 更新 Docker 入口脚本

---

docker-entrypoint.sh
docker/Dockerfile

- 为多个目录和文件设置正确的用户权限，确保容器内应用可以正常访问
- 添加 mxcad 下载来源注释，提高 Dockerfile 可读性

ci: 更新 Docker 构建和运行时权限设置

---

docker/Dockerfile

- 更新 mxcad 下载链接中的版本号
- 修正 mxcad 解压目录名称 -优化变量使用，提高代码可读性

build(docker): 更新 mxcad 下载链接和安装过程

---

Dockerfile
pom.xml
src/main/java/com/jmal/clouddisk/controller/rest/HealthCheckController.java
src/main/resources/application.yml
src/test/java/com/jmal/clouddisk/lucene/ReadPDFTest.java

- 更新 logging 配置，关闭 epub 相关日志
- 在 Dockerfile 中添加健康检查命令 -升级 spring-boot-starter-parent版本到 3.5.3

perf:优化应用配置和 Docker 镜像

---

src/main/java/com/jmal/clouddisk/config/WebConfig.java
src/main/java/com/jmal/clouddisk/controller/rest/DirectLinkController.java
src/main/java/com/jmal/clouddisk/interceptor/DirectFileInterceptor.java
src/main/java/com/jmal/clouddisk/interceptor/FileInterceptor.java
src/main/java/com/jmal/clouddisk/interceptor/PreFileInterceptor.java
src/main/java/com/jmal/clouddisk/interceptor/ShareFileInterceptor.java
src/main/java/com/jmal/clouddisk/listener/FileMonitor.java
src/main/java/com/jmal/clouddisk/model/DirectLink.java
src/main/java/com/jmal/clouddisk/service/impl/DirectLinkService.java
src/main/java/com/jmal/clouddisk/service/impl/FileServiceImpl.java
src/main/java/com/jmal/clouddisk/service/impl/ShareServiceImpl.java

- 新增 DirectFileInterceptor处理直链下载请求
- 添加 DirectLink 模型类用于存储直链信息
- 实现 DirectLinkController 提供直链相关接口
- 完善 DirectLinkService 处理直链生成和重置逻辑
- 调整 FileServiceImpl 中的文件下载方法
- 优化 PreFileInterceptor 中的内部 token 生成和验证逻辑
- 更新 ShareFileInterceptor 移除内部 token 相关代码- 在 WebConfig 中注册 DirectFileInterceptor

feat: 添加直链功能

---

src/main/java/com/jmal/clouddisk/lucene/EtagService.java
src/main/resources/application.yml

- 将 EtagService 中的信息日志级别改为调试级别
- 更新 application.yml 中的日志配置:
- nl.siegmann.epublib.epub 日志级别改为 off
- 新增 org.apache.pdfbox 日志级别为 off

perf:优化日志级别和配置

---

src/main/java/com/jmal/clouddisk/config/WebConfig.java
src/main/java/com/jmal/clouddisk/controller/ArticlesController.java
src/main/java/com/jmal/clouddisk/controller/rest/HealthCheckController.java
src/main/java/com/jmal/clouddisk/controller/sse/SseController.java
src/main/java/com/jmal/clouddisk/oss/web/OssController.java

- 修改 ArticlesController 中的默认路由重定向到 /public/api
- 在 HealthCheckController、OssController 和 SseController 中添加 Swagger 标签注解
- 更新 WebConfig 中的拦截器排除路径，增加对根路径的排除

refactor(controller): 调整路由和接口标签

---

src/main/java/com/jmal/clouddisk/controller/rest/HealthCheckController.java

- 将 @Tag 注解的 name 属性从 "healthCheck" 修改为 "健康检查"
- 这个改动使得 API 文档中的标签名称更加符合中文语境，提高了可读性和易理解性

refactor: 更新 HealthCheckController 类的标签名称

---

pom.xml
src/main/java/com/jmal/clouddisk/config/EncryptionConfig.java
src/main/java/com/jmal/clouddisk/config/EncryptionKeyProvider.java
src/main/java/com/jmal/clouddisk/config/TotpConfig.java
src/main/java/com/jmal/clouddisk/controller/record/LoginResponse.java
src/main/java/com/jmal/clouddisk/controller/record/MfaSetupResponse.java
src/main/java/com/jmal/clouddisk/controller/record/MfaVerifyRequest.java
src/main/java/com/jmal/clouddisk/controller/rest/AuthController.java
src/main/java/com/jmal/clouddisk/controller/rest/MfaController.java
src/main/java/com/jmal/clouddisk/model/rbac/ConsumerDO.java
src/main/java/com/jmal/clouddisk/model/rbac/ConsumerDTO.java
src/main/java/com/jmal/clouddisk/service/IAuthService.java
src/main/java/com/jmal/clouddisk/service/IUserService.java
src/main/java/com/jmal/clouddisk/service/impl/AuthServiceImpl.java
src/main/java/com/jmal/clouddisk/service/impl/TotpService.java
src/main/java/com/jmal/clouddisk/service/impl/UserServiceImpl.java
src/main/resources/file.yml
src/main/resources/i18n/messages.properties
src/main/resources/i18n/messages_en_US.properties
src/main/resources/i18n/messages_zh_CN.properties
src/test/java/com/jmal/clouddisk/WordCoverTest.java

- 新增 MFA（多因素认证）相关功能，包括 TOTP 验证
- 在用户登录时增加 MFA验证步骤
- 实现 MFA 密钥生成、二维码生成和验证功能
- 更新用户信息，支持 MFA 相关字段
- 新增相关配置文件和依赖

feat: 新增两步验证功能
